"""add dish, recipe

Revision ID: 441a0543d135
Revises: d4ccc66dd7f3
Create Date: 2024-07-25 15:07:12.079926

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "441a0543d135"
down_revision: Union[str, None] = "d4ccc66dd7f3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dish",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name_dish", sa.String(length=30), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dish")),
    )
    op.create_table(
        "recipe",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dish_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name_recipe", sa.String(length=264), nullable=False),
        sa.Column("count_views", sa.Integer(), nullable=False),
        sa.Column("ingredients", sa.String(length=264), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.ForeignKeyConstraint(
            ["dish_id"],
            ["dish.id"],
            name=op.f("fk_recipe_dish_id_dish"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("fk_recipe_user_id_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recipe")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("recipe")
    op.drop_table("dish")
    # ### end Alembic commands ###
