"""add nickname for users

Revision ID: 5966fc21e90a
Revises: 03abc0fef553
Create Date: 2024-07-27 18:50:38.240121

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5966fc21e90a"
down_revision: Union[str, None] = "03abc0fef553"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("nickname", sa.String(length=30), nullable=True)
    )
    op.create_unique_constraint(op.f("uq_user_nickname"), "user", ["nickname"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_user_nickname"), "user", type_="unique")
    op.drop_column("user", "nickname")
    # ### end Alembic commands ###
