name: Linter

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install black, isort
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black isort

    - name: Run black
      run: |
        black .

    - name: Run isort
      run: |
        isort .